config/routes.rb
Clip::Application.routes.draw do

   devise_for :users, :controllers => {:sessions => 'users/sessions', :passwords => 'users/passwords', :registrations => 'users/registrations',:unlocks => 'users/unlocks' }
   resources :users

   match '/signup', :to => 'users#new'
   match '/about', :to => 'pages#about'
   match '/contact', :to => 'pages#contact'
   match '/help', :to => 'pages#help'
   
   match '/signin',  :to => 'sessions#new'
   match '/signout', :to => 'sessions#destroy' 

   root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", "http://news.railstutorial.org/"%></li>
      <li><%= link_to "Rails Tutorial",'http://www.railstutorial.org/'%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Help", help_path %></li>
      <% if user_signed_in? %>
      <li><%= link_to "Sign out", destroy_user_session_path(current_user), :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
         <% flash.each do |key, value| %>
           <!-- <div class="flash <%= key %>"><%= value %></div> can be user in place below line. but complex as mix of HTML & ERb-->
           <%= content_tag(:div, value, :class => "flash #{key}") %>
        <% end %>
         <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(session[:staysignedin])  if Rails.env.development? %>
      <%= debug(session[:user_id]) if Rails.env.development? %>
      <%= debug(session) if Rails.env.development? %>
      <%= debug(cookies) if Rails.env.development? %>
      <%= debug(cookies[:remember_token]) if Rails.env.development? %>
      <%= debug(current_user) if Rails.env.development? %>
    </div>
  </body>
</html>